modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]]
modId = "litematica"
version = "${version}"
displayName = "Litematica for Forge"
logoFile="icon.png"
authors="masa"
# The description text for the mod (multi line!) (#mandatory)
description= '''
Litematica for Forge
'''

[[dependencies.litematica]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="CLIENT"

[[dependencies.litematica]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.litematica]]
modId="malilib"
mandatory=true
versionRange="[0.12.0,)"
ordering="BEFORE"
side="CLIENT"